apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-service-monitor
  namespace: monitoring
  labels:
    app: prometheus-operator 
    release: my-prometheus-operator
spec:
  endpoints:
  - port: web
    path: /actuator/prometheus
    honorLabels: true 
  namespaceSelector:
    matchNames:
    - monitoring       
  selector:
    matchLabels:
      release: my-prometheus-operator
      self-monitor: "true"
      
